name: Code quality

on:
  pull_request:

concurrency:
  group: code-quality-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  swap:
    name: Check lint, format and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'pnpm'

      - shell: bash
        run: |
          pnpm i --frozen-lockfile
          pnpm run format:check
          pnpm run lint
          pnpm run test
